name: Despliegue a Producción

on:
  push:
    branches:
      - dev_prod

jobs:
  laravel-nuxt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Instalar dependencias Laravel
        run: |
          cd back/laravel
          composer install
          cp .env.example .env  # Copia el archivo .env si no existe
          php artisan key:generate
          php artisan migrate --force  # Configuración de la base de datos Laravel
          
      - name: Instalar dependencias de Nuxt
        run: |
          cd ..\..\nuxt\
          pwd
          npm install

      - name: Verificar directorio actual en Nuxt
        run: ls

      - name: Build de la aplicación Nuxt
        run: npm run build

      - name: Despliegue a Producción
        run: |
          # Aquí coloca tus comandos o scripts para desplegar a producción
